// Files: src/modules/student-violation/domain/entity/StudentViolation.ts
import {ViolationResolution} from "@/modules/student-violation/domain/entity/ViolationResolution";
/**
 * ============================================================
 * STUDENT VIOLATION ENTITY
 * ============================================================
 *
 * Aggregate root representing a disciplinary violation
 * committed by a student.
 *
 * Identity is generated by the database layer.
 * Domain entity does not generate or manage IDs.
 */
export class StudentViolation {

    private constructor(
        readonly id: string,
        readonly studentId: string,
        readonly violationId: string,
        readonly academicYearId: string,
        readonly point: number,
        readonly occurredAt: Date,
        readonly createdAt: Date,
        private resolution: ViolationResolution | null
    ) {}

    /**
     * Factory used when creating a new violation.
     */
    static create(
        studentId: string,
        violationId: string,
        academicYearId: string,
        point: number,
        occurredAt: Date
    ): StudentViolation {

        return new StudentViolation(
            "",
            studentId,
            violationId,
            academicYearId,
            point,
            occurredAt,
            new Date(),
            null
        )

    }

    /**
     * Factory used when reconstructing entity from persistence.
     */
    static reconstitute(
        id: string,
        studentId: string,
        violationId: string,
        academicYearId: string,
        point: number,
        occurredAt: Date,
        createdAt: Date,
        resolution: ViolationResolution | null
    ): StudentViolation {

        return new StudentViolation(
            id,
            studentId,
            violationId,
            academicYearId,
            point,
            occurredAt,
            createdAt,
            resolution
        )

    }

    getResolution(): ViolationResolution | null {
        return this.resolution
    }

    attachResolution(resolution: ViolationResolution): void {
        this.resolution = resolution
    }

    isResolved(): boolean {
        return this.resolution !== null
    }

}